/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;

import java.util.Random;
import java.util.Scanner;

import utils.utils.captcha;

public class App {

    public static void main(String[] args) {
        Random random = new Random();

        Scanner s = new Scanner(System.in);

        captcha c = new captcha(random.nextInt(10000));
        System.out.println("cual es la suma de : " + String.valueOf(c.getOneRandomNumber()) + " y "
                + String.valueOf(c.getTwoRandomNumber()) + " : ");

        int userInput = s.nextInt();

        c.setuserValueCaptcha(userInput);

        if (c.checkSolvedCaptcha()) {
            System.out.println("El captcha fue resuelto con exito f");
        } else {
            System.out.println("El resultado del captcha fue erroneo");
            c.generateNewNumbers();
            System.out.println("cual es la suma de : " + String.valueOf(c.getOneRandomNumber()) + " y "
                    + String.valueOf(c.getTwoRandomNumber()) + " : ");
            userInput = s.nextInt();
            c.setuserValueCaptcha(userInput);
            if (c.checkSolvedCaptcha()) {
                System.out.println("El captcha fue resuelto con exito f");
            }
        }

    }
}
